/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	bolingcavalry_v1 "k8s-customize-controller/pkg/apis/bolingcavalry/v1"
	versioned "k8s-customize-controller/pkg/client/clientset/versioned"
	internalinterfaces "k8s-customize-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "k8s-customize-controller/pkg/client/listers/bolingcavalry/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// ProgrammerInformer provides access to a shared informer and lister for
// Programmers.
type ProgrammerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ProgrammerLister
}

type programmerInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewProgrammerInformer constructs a new informer for Programmer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewProgrammerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				return client.BolingcavalryV1().Programmers(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				return client.BolingcavalryV1().Programmers(namespace).Watch(options)
			},
		},
		&bolingcavalry_v1.Programmer{},
		resyncPeriod,
		indexers,
	)
}

func defaultProgrammerInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewProgrammerInformer(client, meta_v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *programmerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&bolingcavalry_v1.Programmer{}, defaultProgrammerInformer)
}

func (f *programmerInformer) Lister() v1.ProgrammerLister {
	return v1.NewProgrammerLister(f.Informer().GetIndexer())
}
