apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: programmers.bolingcavalry.k8s.io
spec:
  group: bolingcavalry.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: programmers
    singular: programmer
    kind: Programmer
    shortNames:
    - prog
